# NumPy Tutorial

In [1]:
# Importing numpy module
import numpy as np

In [2]:
# Initializing Array
a = np.array([2, 4, 6])

In [25]:
# by default array creaated will be of integer type
a

array([2, 4, 6])

In [6]:
# Initialzing 3-D Array
b = np.array([[1, 2], [3, 4], [5, 6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
# Initializing array with different datatypes
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype = np.float64)

In [9]:
c

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [12]:
# To get size of arrays
print(a.size)
print(b.size)
print(c.size)

3
6
9


In [13]:
# to get the datatype of array
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
int32
float64


In [14]:
# To get the shape / dimension of the array
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(3, 2)
(3, 3)


In [19]:
# to initialize whole array with zeros
z = np.zeros((2,3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# to change the shape/dimension of array
b.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [32]:
# To get minimum/maximum element of an array
print("Minimum =",a.min())
print("Maximum =",a.max())

Minimum = 2
Maximum = 6


In [36]:
# To get sum of all the elements in array
print(a.sum())

# To get sum of all elements according to the axes
print(b.sum(axis = 0)) # this is top to bottom i.e. row wise
print(c.sum(axis = 1)) # this is left to right i.e. column wise

12
[ 9 12]
[ 6. 15. 24.]


In [39]:
# to cal the square root of each element in an array
s = np.sqrt(a)
print(s)

[1.41421356 2.         2.44948974]


In [40]:
# To calculate Standard Deviation
st = np.std(b)
print(st)

1.707825127659933


In [41]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
a.dot(b)

array([[19, 22],
       [43, 50]])